// game resources
    game.resources = [{
    name: "logo",
    type: "image",
    src: "assets/logo/logo_purple.png"
},{
    name: "tilesheet",
    type: "image",
    src: "assets/maps/tilesheet.png"
},{
    name: "cave_tilesheet",
    type: "image",
    src: "assets/maps/cave_tilesheet.png"
},{
    name: "sewer_tilesheet",
    type: "image",
    src: "assets/maps/sewer_tilesheet.png"
},{
    name: "objects_tilesheet",
    type: "image",
    src: "assets/maps/objects_tilesheet.png"
}, {
    name: "test_map",
    type: "tmx",
    src: "assets/maps/test_map.tmx"
}, {
    name: "house",
    type: "tmx",
    src: "assets/maps/house.tmx"
}, {
    name: "cave",
    type: "tmx",
    src: "assets/maps/cave.tmx"
}, {
    name: "sewers",
    type: "tmx",
    src: "assets/maps/sewers.tmx"
}, {
    name: "sewers_menu",
    type: "tmx",
    src: "assets/maps/sewers_menu.tmx"
},  {
    name: "leatherarmor",
    type: "image",
    src: "assets/armors/leatherarmor.png"
},  {
    name: "mailarmor",
    type: "image",
    src: "assets/armors/mailarmor.png"
},  {
    name: "platearmor",
    type: "image",
    src: "assets/armors/platearmor.png"
},  {
    name: "leatherarmor_nohead",
    type: "image",
    src: "assets/armors/leatherarmor_nohead.png"
},  {
    name: "mailarmor_nohead",
    type: "image",
    src: "assets/armors/mailarmor_nohead.png"
},  {
    name: "platearmor_nohead",
    type: "image",
    src: "assets/armors/platearmor_nohead.png"
},  {
    name: "arrow_right",
    type: "image",
    src: "assets/gui/arrow_right.png"
},  {
    name: "arrow_left",
    type: "image",
    src: "assets/gui/arrow_left.png"
},  {
    name: "m_body",
    type: "image",
    src: "assets/player/m_body.png"
},  {
    name: "f_body",
    type: "image",
    src: "assets/player/f_body.png"
},  {
    name: "m_bald",
    type: "image",
    src: "assets/player/m_bald.png"
},  {
    name: "f_long_green",
    type: "image",
    src: "assets/player/f_long_green.png"
},  {
    name: "f_long_blond",
    type: "image",
    src: "assets/player/f_long_blond.png"
},  {
    name: "f_long_brown",
    type: "image",
    src: "assets/player/f_long_brown.png"
},  {
    name: "f_long_red",
    type: "image",
    src: "assets/player/f_long_red.png"
},  {
    name: "f_long_blue",
    type: "image",
    src: "assets/player/f_long_blue.png"
},  {
    name: "f_long_black",
    type: "image",
    src: "assets/player/f_long_black.png"
},  {
    name: "f_long_purple",
    type: "image",
    src: "assets/player/f_long_purple.png"
},  {
    name: "m_short_green",
    type: "image",
    src: "assets/player/m_short_green.png"
},  {
    name: "m_short_blond",
    type: "image",
    src: "assets/player/m_short_blond.png"
},  {
    name: "m_short_brown",
    type: "image",
    src: "assets/player/m_short_brown.png"
},  {
    name: "m_short_red",
    type: "image",
    src: "assets/player/m_short_red.png"
},  {
    name: "m_short_blue",
    type: "image",
    src: "assets/player/m_short_blue.png"
},  {
    name: "m_short_black",
    type: "image",
    src: "assets/player/m_short_black.png"
},  {
    name: "m_short_purple",
    type: "image",
    src: "assets/player/m_short_purple.png"
},  {
    name: "m_mohawk_green",
    type: "image",
    src: "assets/player/m_mohawk_green.png"
},  {
    name: "m_mohawk_blond",
    type: "image",
    src: "assets/player/m_mohawk_blond.png"
},  {
    name: "m_mohawk_brown",
    type: "image",
    src: "assets/player/m_mohawk_brown.png"
},  {
    name: "m_mohawk_red",
    type: "image",
    src: "assets/player/m_mohawk_red.png"
},  {
    name: "m_mohawk_blue",
    type: "image",
    src: "assets/player/m_mohawk_blue.png"
},  {
    name: "m_mohawk_black",
    type: "image",
    src: "assets/player/m_mohawk_black.png"
},  {
    name: "m_mohawk_purple",
    type: "image",
    src: "assets/player/m_mohawk_purple.png"
},  {
    name: "f_mohawk_green",
    type: "image",
    src: "assets/player/f_mohawk_green.png"
},  {
    name: "f_mohawk_blond",
    type: "image",
    src: "assets/player/f_mohawk_blond.png"
},  {
    name: "f_mohawk_brown",
    type: "image",
    src: "assets/player/f_mohawk_brown.png"
},  {
    name: "f_mohawk_red",
    type: "image",
    src: "assets/player/f_mohawk_red.png"
},  {
    name: "f_mohawk_blue",
    type: "image",
    src: "assets/player/f_mohawk_blue.png"
},  {
    name: "f_mohawk_black",
    type: "image",
    src: "assets/player/f_mohawk_black.png"
},  {
    name: "f_mohawk_purple",
    type: "image",
    src: "assets/player/f_mohawk_purple.png"
},  {
    name: "f_mikado_green",
    type: "image",
    src: "assets/player/f_mikado_green.png"
},  {
    name: "f_mikado_blond",
    type: "image",
    src: "assets/player/f_mikado_blond.png"
},  {
    name: "f_mikado_brown",
    type: "image",
    src: "assets/player/f_mikado_brown.png"
},  {
    name: "f_mikado_red",
    type: "image",
    src: "assets/player/f_mikado_red.png"
},  {
    name: "f_mikado_blue",
    type: "image",
    src: "assets/player/f_mikado_blue.png"
},  {
    name: "f_mikado_black",
    type: "image",
    src: "assets/player/f_mikado_black.png"
},  {
    name: "f_mikado_purple",
    type: "image",
    src: "assets/player/f_mikado_purple.png"
},  {
    name: "f_dreads_green",
    type: "image",
    src: "assets/player/f_dreads_green.png"
},  {
    name: "f_dreads_blond",
    type: "image",
    src: "assets/player/f_dreads_blond.png"
},  {
    name: "f_dreads_brown",
    type: "image",
    src: "assets/player/f_dreads_brown.png"
},  {
    name: "f_dreads_red",
    type: "image",
    src: "assets/player/f_dreads_red.png"
},  {
    name: "f_dreads_blue",
    type: "image",
    src: "assets/player/f_dreads_blue.png"
},  {
    name: "f_dreads_black",
    type: "image",
    src: "assets/player/f_dreads_black.png"
},  {
    name: "f_dreads_purple",
    type: "image",
    src: "assets/player/f_dreads_purple.png"
},  {
    name: "f_emo_green",
    type: "image",
    src: "assets/player/f_emo_green.png"
},  {
    name: "f_emo_blond",
    type: "image",
    src: "assets/player/f_emo_blond.png"
},  {
    name: "f_emo_brown",
    type: "image",
    src: "assets/player/f_emo_brown.png"
},  {
    name: "f_emo_red",
    type: "image",
    src: "assets/player/f_emo_red.png"
},  {
    name: "f_emo_blue",
    type: "image",
    src: "assets/player/f_emo_blue.png"
},  {
    name: "f_emo_black",
    type: "image",
    src: "assets/player/f_emo_black.png"
},  {
    name: "f_emo_purple",
    type: "image",
    src: "assets/player/f_emo_purple.png"
}
//-------------------------ITEMS--------------------------
    , {
    name: "burger",
    type: "image",
    src: "assets/entities/burger.png"
}, {
    name: "money-1",
    type: "image",
    src: "assets/entities/money-1.png"
}, {
    name: "money-2",
    type: "image",
    src: "assets/entities/money-2.png"
}, {
    name: "money-3",
    type: "image",
    src: "assets/entities/money-3.png"
}, {
    name: "money-4",
    type: "image",
    src: "assets/entities/money-4.png"
}, {
    name: "item-flask-red",
    type: "image",
    src: "assets/items/item-flask-red.png"
}, {
    name: "item-axe",
    type: "image",
    src: "assets/items/item-axe.png"
}, {
    name: "item-morningstar",
    type: "image",
    src: "assets/items/item-morningstar.png"
}, {
    name: "item-sword1",
    type: "image",
    src: "assets/items/item-sword1.png"
}, {
    name: "item-sword2",
    type: "image",
    src: "assets/items/item-sword2.png"
}, {
    name: "item-bluesword",
    type: "image",
    src: "assets/items/item-bluesword.png"
}, {
    name: "item-redsword",
    type: "image",
    src: "assets/items/item-redsword.png"
}, {
    name: "item-goldensword",
    type: "image",
    src: "assets/items/item-goldensword.png"
}, {
    name: "item-leatherarmor",
    type: "image",
    src: "assets/items/item-leatherarmor.png"
}, {
    name: "item-mailarmor",
    type: "image",
    src: "assets/items/item-mailarmor.png"
}, {
    name: "item-platearmor",
    type: "image",
    src: "assets/items/item-platearmor.png"
}
//------------------WEAPONS--------------------
,{
    name: "spell_fireball_effect",
    type: "image",
    src: "assets/spells/spell_fireball_effect.png"
},{
    name: "spell_fireball_icon",
    type: "image",
    src: "assets/gui/spell_fireball_icon.png"
},{
    name: "explosion",
    type: "image",
    src: "assets/spells/explosion.png"
},{
    name: "spell_iceball_effect",
    type: "image",
    src: "assets/spells/iceball.png"
},{
    name: "spell_health_anim",
    type: "image",
    src: "assets/spells/spell_health_anim.png"
},{
    name: "spell_health_icon",
    type: "image",
    src: "assets/gui/spell_health_icon.png"
},{
    name: "book",
    type: "image",
    src: "assets/gui/book.png"
},{
    name: "book_tag",
    type: "image",
    src: "assets/gui/book_tag.png"
}
//-------------------MAGIC-------------------------
    , {
    name: "axe",
    type: "image",
    src: "assets/weapons/weapon-axe.png"
}, {
    name: "sword1",
    type: "image",
    src: "assets/weapons/weapon-sword1.png"
}, {
    name: "sword2",
    type: "image",
    src: "assets/weapons/weapon-sword2.png"
}, {
    name: "bluesword",
    type: "image",
    src: "assets/weapons/weapon-bluesword.png"
}, {
    name: "redsword",
    type: "image",
    src: "assets/weapons/weapon-redsword.png"
}, {
    name: "goldensword",
    type: "image",
    src: "assets/weapons/weapon-goldensword.png"
}, {
    name: "morningstar",
    type: "image",
    src: "assets/weapons/weapon-morningstar.png"
}, {
    name: "target",
    type: "image",
    src: "assets/entities/target.png"
},  {
    name: "npc_firefox",
    type: "image",
    src: "assets/npcs/npc_firefox.png"
},  {
    name: "npc_bat",
    type: "image",
    src: "assets/npcs/npc_bat.png"
}, {
    name: "npc_guard",
    type: "image",
    src: "assets/npcs/npc_guard.png"
}, {
    name: "npc_king",
    type: "image",
    src: "assets/npcs/npc_king.png"
}, {
    name: "npc_priest",
    type: "image",
    src: "assets/npcs/npc_priest.png"
}, {
    name: "npc_villager",
    type: "image",
    src: "assets/npcs/npc_villager.png"
}, {
    name: "npc_blacksmith",
    type: "image",
    src: "assets/npcs/npc_blacksmith.png"
}, {
    name: "npc_octocat",
    type: "image",
    src: "assets/npcs/npc_octocat.png"
}, {
    name: "npc_zaraka",
    type: "image",
    src: "assets/npcs/npc_zaraka.png"
}, {
    name: "npc_rat",
    type: "image",
    src: "assets/npcs/npc_rat.png"
}, {
    name: "npc_sorcerer",
    type: "image",
    src: "assets/npcs/npc_sorcerer.png"
}, 
/***************ENEMIES****************/
    {
    name: "npc_goblin",
    type: "image",
    src: "assets/npcs/npc_goblin.png"
}, {
    name: "npc_crab",
    type: "image",
    src: "assets/npcs/npc_crab.png"
},{
    name: "chest_dungeon",
    type: "image",
    src: "assets/entities/chest_dungeon.png"
}, {
    name: "chest_player",
    type: "image",
    src: "assets/entities/chest_player.png"
}, {
    name: "shadow16",
    type: "image",
    src: "assets/entities/shadow16.png"
},{
    name: "sparks",
    type: "image",
    src: "assets/entities/sparks.png"
},{
    name: "rain",
    type: "image",
    src: "assets/entities/rain.png"
},{
    name: "barrel",
    type: "image",
    src: "assets/entities/barrel.png"
},{
    name: "close_button",
    type: "image",
    src: "assets/gui/close_button.png"
},{
    name: "inventory_tile",
    type: "image",
    src: "assets/gui/inventory_tile.png"
},{
    name: "checkbox_unchecked",
    type: "image",
    src: "assets/gui/checkbox_unchecked.png"
},{
    name: "checkbox_checked",
    type: "image",
    src: "assets/gui/checkbox_checked.png"
},{
    name: "undefined",
    type: "image",
    src: "assets/gui/undefined.png"
},{
    name: "backpack",
    type: "image",
    src: "assets/gui/backpack.png"
},{
    name: "backpack_icon",
    type: "image",
    src: "assets/gui/backpack_icon.png"
},{
    name: "options_icon",
    type: "image",
    src: "assets/gui/options_icon.png"
},{
    name: "death",
    type: "image",
    src: "assets/entities/death.png"
},{
    name: "firecamp1",
    type: "image",
    src: "assets/entities/firecamp1.png"
},{
    name: "particle",
    type: "image",
    src: "assets/entities/particle.png"
},{
    name: "particle2",
    type: "image",
    src: "assets/entities/particle2.png"
},{
    name: "particle3",
    type: "image",
    src: "assets/entities/particle3.png"
},{
    name: "8x8Font",
    type: "image",
    src: "assets/fonts/8x8Font-white.png"
},{
    name: "geebeeyay-8x8",
    type: "image",
    src: "assets/fonts/geebeeyay-8x8.png"
},{
    name: "gold_8x8",
    type: "image",
    src: "assets/fonts/gold_8x8.png"
},
//--------------------------SOUNDS-----------------------
    {
    name: "itempick2",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "leather",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "metal-clash",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "exp_click",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "fire",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "level_up",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "swing",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "bottle",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "coins",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "chest_open",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "chest_close",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "rain",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "forest",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "turn_page",
    type: "audio",
    src: "assets/sounds/"
},
/***************SOUNDTRACK**********************/
    {
    name: "taberna_noctis",
    type: "audio",
    src: "assets/sounds/"
}, {
    name: "battle_of_souls",
    type: "audio",
    src: "assets/sounds/"
},
//----------------------DIALOGS--------------------------
{
    name: "dialog_guard",
    type: "json",
    src: "assets/dialogs/guard.json"
}, {
    name: "dialog_king",
    type: "json",
    src: "assets/dialogs/king.json"
},{
    name: "dialog_priest",
    type: "json",
    src: "assets/dialogs/priest.json"
},{
    name: "dialog_octocat",
    type: "json",
    src: "assets/dialogs/octocat.json"
},{
    name: "dialog_chest",
    type: "json",
    src: "assets/dialogs/chest.json"
},{
    name: "dialog_zaraka",
    type: "json",
    src: "assets/dialogs/zaraka.json"
},{
    name: "dialog_villager",
    type: "json",
    src: "assets/dialogs/villager.json"
},{
    name: "dialog_blacksmith",
    type: "json",
    src: "assets/dialogs/blacksmith.json"
},{
    name: "dialog_wizard",
    type: "json",
    src: "assets/dialogs/wizard.json"
}];